//! Slash command definitions and code snippets.

/// Command with description for completion display.
pub(super) struct CommandDef {
    pub name: &'static str,
    pub description: &'static str,
    /// Parameter hints for the command
    pub params: &'static [&'static str],
}

/// Code snippet for completion.
pub(super) struct CodeSnippet {
    pub trigger: &'static str,
    pub description: &'static str,
    pub content: &'static str,
}

pub(super) const CODE_SNIPPETS: &[CodeSnippet] = &[
    CodeSnippet { trigger: "fn", description: "函数定义", content: "fn name() {\n    \n}" },
    CodeSnippet { trigger: "if", description: "条件语句", content: "if condition {\n    \n}" },
    CodeSnippet { trigger: "for", description: "循环", content: "for item in collection {\n    \n}" },
    CodeSnippet { trigger: "match", description: "模式匹配", content: "match value {\n    Pattern => {},\n    _ => {},\n}" },
    CodeSnippet { trigger: "struct", description: "结构体", content: "struct Name {\n    field: Type,\n}" },
    CodeSnippet { trigger: "enum", description: "枚举", content: "enum Name {\n    Variant1,\n    Variant2,\n}" },
    CodeSnippet { trigger: "impl", description: "实现块", content: "impl Name {\n    pub fn new() -> Self {\n        Self {}\n    }\n}" },
    CodeSnippet { trigger: "trait", description: "特征", content: "trait Name {\n    fn method(&self);\n}" },
    CodeSnippet { trigger: "async", description: "异步函数", content: "async fn name() -> Result<(), Error> {\n    Ok(())\n}" },
    CodeSnippet { trigger: "test", description: "测试函数", content: "#[test]\nfn test_name() {\n    assert!(true);\n}" },
    CodeSnippet { trigger: "print", description: "打印宏", content: "println!(\"{}\", value);" },
    CodeSnippet { trigger: "vec", description: "向量", content: "vec![]" },
    CodeSnippet { trigger: "hashmap", description: "哈希映射", content: "HashMap::new()" },
    CodeSnippet { trigger: "result", description: "结果类型", content: "Result<T, E>" },
    CodeSnippet { trigger: "option", description: "选项类型", content: "Option<T>" },
];

pub(super) const SLASH_COMMANDS: &[CommandDef] = &[
    CommandDef { name: "/help", description: "显示帮助信息", params: &[] },
    CommandDef { name: "/quit", description: "退出程序", params: &[] },
    CommandDef { name: "/exit", description: "退出程序", params: &[] },
    CommandDef { name: "/mode", description: "切换模式", params: &["plan", "agent", "yolo"] },
    CommandDef { name: "/compact", description: "压缩上下文", params: &["<instructions>"] },
    CommandDef { name: "/memory", description: "显示记忆面板", params: &[] },
    CommandDef { name: "/tools", description: "显示工具面板", params: &[] },
    CommandDef { name: "/stats", description: "显示统计面板", params: &[] },
    CommandDef { name: "/sessions", description: "列出已保存会话", params: &[] },
    CommandDef { name: "/resume", description: "恢复已保存会话", params: &["<session-id>"] },
    CommandDef { name: "/cost", description: "显示费用明细", params: &[] },
    CommandDef { name: "/config", description: "查看/修改配置", params: &["export", "import", "history", "sync", "rollback"] },
    CommandDef { name: "/config export", description: "导出配置", params: &[] },
    CommandDef { name: "/config import", description: "导入配置", params: &["<file>"] },
    CommandDef { name: "/config history", description: "配置历史", params: &[] },
    CommandDef { name: "/config sync", description: "同步配置", params: &[] },
    CommandDef { name: "/config rollback", description: "回滚配置", params: &["<version>"] },
    CommandDef { name: "/doctor", description: "环境诊断", params: &[] },
    CommandDef { name: "/clear", description: "清空对话", params: &[] },
    CommandDef { name: "/vim", description: "切换 Vim 模式", params: &[] },
    CommandDef { name: "/init", description: "生成 MAIX.md", params: &["force"] },
    CommandDef { name: "/model", description: "切换模型", params: &["<model-name>"] },
    CommandDef { name: "/identity", description: "身份管理", params: &[] },
    CommandDef { name: "/architecture", description: "架构管理", params: &[] },
    CommandDef { name: "/skill", description: "技能管理", params: &[] },
    CommandDef { name: "/task", description: "任务队列管理", params: &[] },
    CommandDef { name: "/health", description: "健康检查", params: &[] },
    CommandDef { name: "/export", description: "导出对话为 Markdown", params: &["<filename>"] },
    CommandDef { name: "/desk", description: "显示工作台面板", params: &[] },
    CommandDef { name: "/note add", description: "添加便签", params: &["<content>"] },
    CommandDef { name: "/pin", description: "固定文件到工作台", params: &["<file>"] },
    CommandDef { name: "/task_add", description: "添加任务到工作台", params: &["<title>"] },
    CommandDef { name: "/timestamp", description: "开关时间戳", params: &[] },
    CommandDef { name: "/fullscreen", description: "开关全屏模式", params: &[] },
    CommandDef { name: "/sound", description: "开关声音提醒", params: &[] },
    CommandDef { name: "/git", description: "Git 状态", params: &[] },
    CommandDef { name: "/remind", description: "设置定时提醒", params: &["<time>", "<message>"] },
    CommandDef { name: "/reminders", description: "查看提醒列表", params: &[] },
    CommandDef { name: "/todo", description: "待办事项管理", params: &["add", "done", "start", "rm", "list"] },
    CommandDef { name: "/todo add", description: "添加待办", params: &["<content>"] },
    CommandDef { name: "/todo done", description: "完成待办", params: &["<id>"] },
    CommandDef { name: "/todo start", description: "开始待办", params: &["<id>"] },
    CommandDef { name: "/todo rm", description: "删除待办", params: &["<id>"] },
    CommandDef { name: "/todo list", description: "列出待办", params: &[] },
    CommandDef { name: "/theme", description: "切换主题", params: &["dark", "light", "solarized", "dracula"] },
    CommandDef { name: "/layout", description: "切换布局", params: &["standard", "compact", "relaxed", "focus"] },
    CommandDef { name: "/keys", description: "快捷键方案", params: &["standard", "vim", "emacs"] },
    CommandDef { name: "/tutorial", description: "交互式教程", params: &[] },
    CommandDef { name: "/quickstart", description: "快速入门卡片", params: &[] },
    CommandDef { name: "/tips", description: "最佳实践提示", params: &[] },
    CommandDef { name: "/usage", description: "使用统计", params: &[] },
    CommandDef { name: "/feedback", description: "提交反馈", params: &["<content>"] },
    CommandDef { name: "/profile", description: "用户配置管理", params: &["save", "load"] },
    CommandDef { name: "/calendar", description: "显示日历", params: &[] },
    CommandDef { name: "/habit", description: "习惯追踪", params: &["add", "done", "rm", "list"] },
    CommandDef { name: "/habit add", description: "添加习惯", params: &["<name>"] },
    CommandDef { name: "/habit done", description: "完成习惯", params: &["<id>"] },
    CommandDef { name: "/habit rm", description: "删除习惯", params: &["<id>"] },
    CommandDef { name: "/habit list", description: "列出习惯", params: &[] },
    CommandDef { name: "/profile save", description: "保存配置", params: &["<name>"] },
    CommandDef { name: "/profile load", description: "加载配置", params: &["<name>"] },
    CommandDef { name: "/tag", description: "会话标签管理", params: &["add", "rm"] },
    CommandDef { name: "/tag add", description: "添加标签", params: &["<name>"] },
    CommandDef { name: "/tag rm", description: "删除标签", params: &["<name>"] },
    CommandDef { name: "/tool_perms", description: "工具权限管理", params: &["add", "rm", "list"] },
    CommandDef { name: "/tool_perms add", description: "添加权限", params: &["<tool>", "auto|manual", "risk_level"] },
    CommandDef { name: "/tool_perms rm", description: "删除权限", params: &["<tool>"] },
    CommandDef { name: "/tool_perms list", description: "列出权限", params: &[] },
    CommandDef { name: "/session merge", description: "合并会话", params: &["<session-id>"] },
    CommandDef { name: "/session compare", description: "比较会话", params: &["<session-id>"] },
    CommandDef { name: "/session replay", description: "回放会话", params: &[] },
    CommandDef { name: "/session share", description: "分享会话", params: &[] },
    CommandDef { name: "/export html", description: "导出为 HTML", params: &[] },
    CommandDef { name: "/tool_chain", description: "工具链管理", params: &["add", "run", "rm", "list"] },
    CommandDef { name: "/tool_chain add", description: "创建工具链", params: &["<name>", "<tool1>", "<tool2>"] },
    CommandDef { name: "/tool_chain run", description: "执行工具链", params: &["<name>"] },
    CommandDef { name: "/tool_chain rm", description: "删除工具链", params: &["<name>"] },
    CommandDef { name: "/tool_template", description: "工具模板管理", params: &["save", "load", "rm", "list"] },
    CommandDef { name: "/tool_template save", description: "保存工具模板", params: &["<name>", "<tool1>", "<tool2>"] },
    CommandDef { name: "/tool_template load", description: "加载工具模板", params: &["<name>"] },
    CommandDef { name: "/tool_template rm", description: "删除工具模板", params: &["<name>"] },
    CommandDef { name: "/tool_parallel", description: "并行执行工具", params: &["<tool1>", "<tool2>"] },
];
